### ISSUE TITLE
fatal error: src/shared/io.h: No such file or directory

### ISSUE THREAD

**Issue by lyangmdrs** [jjjsmit/BluetoothBLEClient#1]
running: 

`gcc bleClient.c 'pkg-config --cflags --libs glib-2.0' 'pkg-config --cflags dbus-1'  -o client`

i've got:

`bleClient.c:167:10: fatal error: src/shared/io.h: No such file or directory`

**Comment by edgargrimberg** [comment]
In the Makefile, set BLUEZ_BASE to the base of the Bluez source code
